### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by nogweii** [opnsense/changelog#2]
So I can subscribe to it in my feed reader of choice (Newsblur) and be a bit quicker about actually noticing updates.

**Comment by fichtner** [comment]
This should work for you: https://opnsense.org/blog/feed/ :)

**Comment by nogweii** [comment]
Ah, hah! I didn't notice that URL -- it's not linked anywhere obvious nor is it discoverable using the standard `<link>`.

Could you add it?

```html
<link rel="alternate" type="application/rss+xml" title="Opnsense Blog" href="https://opnsense.org/blog/feed/" />
```

**Comment by fichtner** [comment]
Sure, will forward it to the site admins. 

Thanks,
Franco

**Comment by fichtner** [comment]
It was added. Will appreciate the hint if it works correctly. :)


Cheers,
Franco

**Comment by nogweii** [comment]
Yep, it works! Autodiscovery of the RSS feed succeeds and the feed reader can successfully subscribe. Thanks for adding the tag!

**Comment by fichtner** [comment]
Thanks for reporting ❤️
